---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "oracle"
    #mypassword: "P@ssw0rd1"
  vars_files:
    - /root/Ansible_Projects/sep_deploy/orapwd.yml
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ my_password | password_hash('sha512') }}"
...
