---
- name: Deploy a new VM from template
  hosts: all
  gather_facts: no
  collections:
    - community.vmware
  extra_vars:
    vcenter_hostname
  
  tasks:
    - name: Deploy VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        datastore: "{{ datastore_name }}"
        networks:
          - name: "{{ network_name }}"
        hardware:
          memory_mb: 4096
          num_cpus: 2
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy_result

    - name: Display VM IP
      debug:
        msg: "The new VM's IP address is {{ deploy_result.instance.ipv4 }}"
